# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: aeb6545918b7dbabadab7a1005c9933b0f2d36eabf4e9b45930fe275c33eeff0981f2b3499acae675c4af9a2d37cb905bd6fea68dbe794c4d1bf355243b9d59c

test:
  secret_key_base: dccc49df7006d3492dfcdb7aff63bebf62d7a14eb1e7715d4447bbb6bae6832420b051e0d53328e1628ae10bdd21df54e1884243352a8cb8523c649218b62e81

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
